name: CI

on: [ push ]
#-> bei welchem Event diese Aufgabe (Job) erfüllt werden soll (hier wenn wir Code in Mainbranch pushen)

#was ausgeführt werden soll:
jobs:
  test:
    runs-on: ubuntu-latest
    steps: #was JEWEILS ausgeführt werden soll:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
      - name: clean build
        run: ./gradlew clean test --info --stacktrace